### ISSUE TITLE
Reports files without duplicated code

### ISSUE THREAD

**Issue by cgutierr-zgz** [platisd/duplicate-code-detection-tool#17]
Hi, I've been using this GH Action and set `ignore_below: 20`, tool anyway shows up, even when there's no similarities found whatsoever

Example:
![Screenshot 2022-07-29 at 14 56 51](https://user-images.githubusercontent.com/18635739/181765471-2952a3fe-d66e-448c-8612-b4f7943a155b.png)

I might be doing something wrong, but I've literally copied over from the example provided

Thanks

**Comment by platisd** [comment]
Hello there, is this on a public repo? If so do you have a link to a pull request?

**Comment by cgutierr-zgz** [comment]
> Hello there, is this on a public repo? If so do you have a link to a pull request?

Sadly it's on a private repo
I have it like follows
```yaml
   - name: 🕵️ Check for duplicate code
        uses: platisd/duplicate-code-detection-tool@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directories: "src/app"
          # Only examine .ts files
          file_extensions: "ts"
          # Only report similarities above 20%
          ignore_below: 20
          # If a file is more than 99% similar to another, then the job fails
          # This should probably be around 70% in the future
          fail_above: 99
          # If a file is more than 20% similar to another, show a warning symbol in the report
          warn_above: 20
```

It's reporting files as I showed in the screenshot on top

Maybe I have something written bad in the yaml, but I can't seem to find it
