### ISSUE TITLE
Reuse of the previous comment

### ISSUE THREAD

**Issue by idzm** [platisd/duplicate-code-detection-tool#27]
It better to reuse (overwrite) existing comment (which starts with `Duplicate code detection tool report`) to avoid being overloaded by bot comments.

**Comment by platisd** [comment]
:thinking: Don't know...
Assuming there's a large pull request, which includes discussions etc, it will not be obvious which version of the code the report is about. Additionally, any "progress" will not be visible either.

On what events are you having the Action triggered? My recommendation would be to trigger it only based on a keyword/comment to decrease the spam.

**Comment by idzm** [comment]
Action is triggered by `pull_request` event. Many services ([codecov](https://github.com/apps/codecov), [sonarcloud](https://github.com/apps/sonarcloud)) reuse previous comment. To save history we can just rewrite previous comment.

**Comment by platisd** [comment]
Sonarcloud seems to leave new comments, at least in the [configuration](https://github.com/platisd/smartcar_shield/blob/master/sonar-project.properties) I have:
![image](https://github.com/platisd/duplicate-code-detection-tool/assets/7327776/c221e85a-3fb6-428b-9909-283b0456a7be)

Codecov seems to be reusing the same comment:
![image](https://github.com/platisd/duplicate-code-detection-tool/assets/7327776/3c16076b-2a9b-48c2-a2fe-32b2577a11a9)

My suggestion is to make this an opt-in feature via a property in the `yml` file.

E.g., `one_comment: true` which defaults to `false`:

```yaml
name: Duplicate code

on: pull_request

jobs:
  duplicate-code-check:
    name: Check for duplicate code
    runs-on: ubuntu-20.04
    steps:
      - name: Check for duplicate code
        uses: platisd/duplicate-code-detection-tool@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          one_comment: true
          directories: "src/, test/ut"
```

Feel free to submit a pull request that provides this feature. :100:
