### ISSUE TITLE
Error: not enought source code fles

### ISSUE THREAD

**Issue by lukaas33** [platisd/duplicate-code-detection-tool#34]
I want to use this action in my node js project.
My github action is setup as follows:

```
name: Duplicate code detection

on: pull_request

jobs:
  duplicate-code-check:
    name: Check for duplicate code
    runs-on: ubuntu-20.04
    steps:
      - name: Check for duplicate code
        uses: platisd/duplicate-code-detection-tool@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directories: "."
```

I am getting the following error:

```
 * [new ref]         refs/pull/120/head -> pull_request_branch
Switched to branch 'pull_request_branch'
Not enough source code files found
Action aborted due to bad user input
```

**Comment by platisd** [comment]
Hi! Can you try:
- `directories: "./"` instead of `directories: "."`
- `ls .` before the action is run to ensure that there are actually files in the directory

And let me know how it went?

**Comment by lukaas33** [comment]
I have ran the following:

```
name: Duplicate code detection

on: pull_request

jobs:
  duplicate-code-check:
    name: Check for duplicate code
    runs-on: ubuntu-20.04
    steps:
      - name: List files in current directory
        run: pwd && ls .
        
      - name: Check for duplicate code
        uses: platisd/duplicate-code-detection-tool@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directories: "./"
``` 

And got this result (repo and username redacted):

```
0s
Run pwd && ls .
  pwd && ls .
  shell: /usr/bin/bash -e {0}
/home/runner/work/[user name]/[repo name]
```
