### ISSUE TITLE
Empty message posted

### ISSUE THREAD

**Issue by lukaas33** [platisd/duplicate-code-detection-tool#35]
Hi, I am using this tool, but it is only posting empty comments. 
Is there any way to check why? This is happenign in a private repo.

This is the config, note that it was also posting empty comments before adding `one_comment: true`

```yml
name: Replication

on: pull_request

jobs:
  duplicate-code-check:
    name: Check for duplicate code
    runs-on: ubuntu-20.04
    steps:     
      - name: Check for duplicate code
        uses: platisd/duplicate-code-detection-tool@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          one_comment: true
````
